# Generated by Django 3.0.6 on 2020-06-07 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="posts.Post",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vote", unique_together={("user_id", "post_id")},
        ),
        migrations.DeleteModel(name="Comment",),
        migrations.RemoveField(model_name="vote", name="content_type",),
        migrations.RemoveField(model_name="vote", name="object_id",),
    ]
